server:
  port: 9991

spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  data:
    redis:
      port: 50001

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen-plus-2025-04-28
      api-key: ${ALI_BL_API_KEY:}
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen-plus-2025-04-28
      api-key: ${ALI_BL_API_KEY:}
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen-plus-2025-04-28
      api-key: ${ALI_BL_API_KEY:}
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10
  # 存储向量
  community:
    redis:
      port: 50001
      dimension: 1024
      index-name: doc_store
